// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwvrzstppfoxebjsivqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13dnJ6c3RwcGZveGVianNpdnFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5ODE1NzEsImV4cCI6MjA3ODU1NzU3MX0.rg27fu5bOASWJxOCnFaoLvojVeEwZivVIrGQuaxQzXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});